name: Docker

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  build-and-test:
    name: build and test images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        
      - name: build
        run: docker-compose build
        
   