name: Docker nightly

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  build-and-test:
    name: build and test images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
   