name: Docker releases

on:
  push:
    branches:
      - 'v*'
    tags-ignore:
      - '*'

jobs:
  build-and-test:
    name: build and test images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    